color0 #131313
color1 #ffb4ab
color2 #8ad88e
color3 #b9ccb5
color4 #a1ced6
color5 #8ad88e
color6 #b9ccb5
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #8ad88e
color11 #b9ccb5
color12 #a1ced6
color13 #8ad88e
color14 #b9ccb5
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #8ad88e
inactive_border_color #474747
url_color             #8ad88e

active_tab_foreground   #003911
active_tab_background   #8ad88e
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
